[package]
name = "hrdwr_info"
version = "0.0.1"
authors = ["GrayDayDev<luca.paradisi@proton.me>"]
description = "Simple hardware analyzer in Rust"
license = "MIT"
repository = ""
edition = "2024"

[dependencies]
sysinfo = "0.34.2"
serde = { version = "1.0.219", features = ["derive"] }
num_cpus = "1.16"
ocl = "0.19.7"